### ISSUE TITLE
https issue with current latest tag

### ISSUE THREAD

**Issue by schnoddelbotz** [justb4/docker-jmeter#16]
My testplans were/are running fine against https servers with `justb4/jmeter:3.3` but with `latest` (i.e. jmeter 5) I get this now:

Uncaught Exception java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLSessionImpl. See log file for details.

**Comment by justb4** [comment]
Indeed, there seems to be problem with SSL/HTTPS connections, is related to Alpine and JDK versions:

* https://bugs.alpinelinux.org/issues/10126
* https://github.com/docker-library/openjdk/issues/289

Fix (install `nss` lib) upcoming...

**Comment by justb4** [comment]
@schnoddelbotz  Should be fixed, can you try to use the `latest` or `5.1.1` version from DockerHub and close this issue if working?

**Comment by schnoddelbotz** [comment]
happily confirming: works like a charm again.
thanks for the quick response, fix ... and the image :)

**Comment by schnoddelbotz** [comment]
Hi @justb4 
Just noticed that current `3.3r2` tag seems also affected. Unsure whether you consider 3.3 as still maintained... Please feel free to re-close issue if not.

**Comment by justb4** [comment]
Hmm, yes, by mistake `3.3r2` was rebuilt where it shouldn't. I removed that version altogether and am pushing a fresh `3.3` built with the latest master. Most folks build their own image anyway.
