### ISSUE TITLE
HTTPS Request Error

### ISSUE THREAD

**Issue by emre141** [justb4/docker-jmeter#18]
Hi
 I test my JMX configuration i have got below exceptions from docker images.

root@ip-172-21-123-216 roles]# docker logs -f a783b4594fec
START Running Jmeter on Tue Apr 30 15:37:13 +03 2019
JVM_ARGS=-Xmn34988m -Xms139952m -Xmx139952m
jmeter args=-s -n -Jclient.rmi.localport=7000 -Jserver.rmi.localport=60000 -JCookieManager.save.cookies=true -Jserver.rmi.ssl.disable=true
Apr 30, 2019 3:37:15 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Using local port: 60000
Created remote object: UnicastServerRef2 [liveRef: [endpoint:[172.18.0.10:60000](local),objID:[25669600:16a6e3fc92c:-7fff, 7522892051062824289]]]
Starting the test on host slave-6 @ Tue Apr 30 15:37:40 EET 2019 (1556627860302)
Uncaught Exception java.lang.ExceptionInInitializerError. See log file for details.
Uncaught Exception java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLSessionImpl. See log file for details.
Uncaught Exception java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLSessionImpl. See log file for details.
Finished the test on host slave-6 @ Tue Apr 30 15:37:44 EET 2019 (1556627864302)

Do you have any idea ?

**Comment by justb4** [comment]
Can you indicate the JMeter version you are running?

Problem looks very similar to issue #16.

**Comment by emre141** [comment]
Hi,
I am using current Dockerfile in this repo which include below application versions

FROM alpine:3.9
ARG JMETER_VERSION="5.1.1"
&& apk add --update openjdk8-jre tzdata curl unzip bash \
&& apk add --no-cache nss \

but i have got same error when i running jmeter https request

**Comment by emre141** [comment]
Ohh no its works fine its my mistake to wrong docker file.Thanks again. image version and jmeter 5.1.1 works well.
