### ISSUE TITLE
NO X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by yjchiu** [justb4/docker-jmeter#20]
When I run your files, I got this error message.
An error occurred:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

Does anyone face the same problem?

**Comment by andrewmadden** [comment]
Any solution for this?

**Comment by HenryGuillen17** [comment]
I also need a solution for this.

**Comment by sparkoo** [comment]
@HenryGuillen17 just pass `-n` to the container

**Comment by subkryl** [comment]
"-n" is already in test.sh args for jmeter. I also added     -Djava.awt.headless=true \ without success.
the final printed command will be : 
jmeter args=-Dlog_level.jmeter=DEBUG     -Djava.awt.headless=true    -n -t tests/trivial/test-plan.jmx -l tests/trivial/test-plan.jtl -j tests/trivial/jmeter.log    -e -o tests/trivial/report

and 

An error occurred: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

**Comment by subkryl** [comment]
It's a problem when passing many words to an argument "-JTARGET_KEYWORD=\"${TARGET_KEYWORD}\"" and passing them through containers and finally the -n option won't be reached. The question is more around how to past space separated list to the entrypoint.sh

**Comment by Bryce-L** [comment]
Why was this closed?  I don't see, or maybe I don't understand, the solution.

```
D:\Git>docker run justb4/jmeter
START Running Jmeter on Wed Jan 20 18:56:05 UTC 2021
JVM_ARGS=-Xmn4698m -Xms18792m -Xmx18792m
jmeter args=
Jan 20, 2021 6:56:06 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
================================================================================
Don't use GUI mode for load testing !, only for Test creation and Test debugging.
For load testing, use CLI Mode (was NON GUI):
   jmeter -n -t [jmx file] -l [results file] -e -o [Path to web report folder]
& increase Java Heap to meet your test requirements:
   Modify current env variable HEAP="-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m" in the jmeter batch file
Check : https://jmeter.apache.org/usermanual/best-practices.html
================================================================================
An error occurred:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```

**Comment by seanbenhur** [comment]
> @HenryGuillen17 just pass `-n` to the container

May I know where should I exactly pass this command?
