### ISSUE TITLE
Windows Docker Image

### ISSUE THREAD

**Issue by get2saravanan88** [justb4/docker-jmeter#22]
Team,

Is there any similar image available for windows Docker. I tried getting this image for windows  but no luck.

Cheers.

-Saravanan S

**Comment by justb4** [comment]
? Docker Images are supposed to be universal.

**Comment by get2saravanan88** [comment]
I got my docker installed on Windows 10 and using minikube. I got this
jmeter image and when I try to execute the run.sh it's removing the result
folder in the image location. Then got into an assumption it's not
compatible .

**Comment by justb4** [comment]
Ok, the `run.sh` is a Shell script, so will not run on Windows. But it is just a shorthand, not essential. You can run the Docker commands in `run.sh` yourself or develop a `.bat` or `.cmd` script. I cannot help you with that.

**Comment by get2saravanan88** [comment]
Thanks for your reply. I just created a .Bat file invoking the test in non
GUI mode. (jmeter -n -t
C:\Windows\System32\docker-jmeter\tests\trivial\test-plan.jmx -l
C:\Windows\System32\docker-jmeter\tests\trivial\test-plan.jtl)  Could you
please help me how this can be done.

**Comment by QAInsights** [comment]
@get2saravanan88 Please check this [repo](https://github.com/QAInsights/windows-docker-jmeter) for Windows container.

**Comment by justb4** [comment]
No reaction over a year. Seemingly solved. Closing.
