### ISSUE TITLE
password

### ISSUE THREAD

**Issue by ihassanvk** [justb4/docker-jmeter#27]
I am trying to execute ./test.sh and ./run.sh but it asks for a password. Where do I find it? Is docker-jmeter restricted or for public use?

**Comment by justb4** [comment]
Reason is the `sudo` statements within the  `./test.sh` and `./run.sh` scripts. Dependent on your setup (Linux, Mac, user-env, `sudoers`-config) you may want to remove those `sudo` prefixes. Or type in the `root` password of your system. If you can run `docker` commands without `sudo` you can remove them.

**Comment by ihassanvk** [comment]
Thank you very much! It never occured to me to use my own system password!
