### ISSUE TITLE
docker run one error occurred

### ISSUE THREAD

**Issue by liangqinwei** [justb4/docker-jmeter#31]
![image](https://user-images.githubusercontent.com/16114633/84338734-6f2cac00-abcf-11ea-9a81-6859e8c567d3.png)

**Comment by espekkaya** [comment]
Hello @liangqinwei ,
That is normal error message. Because you just wanted to open jmeter application window instead of using cli. Please just set params below.

````
export timestamp=$(date +%Y%m%d_%H%M%S) && \
export volume_path=<where files are on host> && \
export jmeter_path=/mnt/jmeter && \
docker run \
  --volume “${volume_path}”:${jmeter_path} \
  jmeter \
  -n <any sequence of jmeter args> \
  -t ${jmeter_path}/<jmx_script> \
  -l ${jmeter_path}/tmp/result_${timestamp}.jtl \
  -j ${jmeter_path}/tmp/jmeter_${timestamp}.log

**Comment by justb4** [comment]
Thanks @liangqinwei . This should solve. Closing.
