### ISSUE TITLE
Any plans to add  plugins  setting functional

### ISSUE THREAD

**Issue by roderick-liu** [justb4/docker-jmeter#33]
hi 
     I need some plugins in jmeter.
    Any plans to add plugins setting functional?

**Comment by qwertynik** [comment]
@justb4 
Any plans of adding support to include plugins. 
Had changed the Dockerfile to load the necessary plugin in the image, but it does not load.

**Comment by andrelramos** [comment]
I created a PR to install jmeter plugins using docker-jmeter https://github.com/justb4/docker-jmeter/pull/35.

You all can use the docker image andrelramos/jmeter while the PR isn't approved.

I added usage instructions on README.md

**Comment by nishant-shah-social** [comment]
@justb4 Can ^ PR be reviewed and merged if all is well.
Some jmeter plugins are really useful. So, its availability in the docker image would really help

**Comment by justb4** [comment]
@nishant-shah-social See #35 - think we can close this issue. re-open if still changes required.
