### ISSUE TITLE
can not run image when using --mount and -v command

### ISSUE THREAD

**Issue by sjoshi-exiger** [justb4/docker-jmeter#41]
I am trying simple jmeter test but want jtl log file in my host machine.
so tried to run image with --mount and -v command.

docker run --mount type=bind,source="E:/xxxxxx/dockerContent",target="/opt/apache-jmeter-5.3/bin" jmeter -n -t  bin/examples/CSVSample.jmx -l bin/example-run1.jtl

docker run -v E/xxxxxxxx/dockerContent:/opt/apache-jmeter-5.3/bin jmeter -n -t  bin/examples/CSVSample.jmx -l bin/example-run1.jtl

but both throws following error error 

START Running Jmeter on Sun Jun  6 12:46:08 CEST 2021
JVM_ARGS=-Xmn2138m -Xms8552m -Xmx8552m
jmeter args=-n -t bin/example.jmx -l bin/example-run1.jtl
/entrypoint.sh: line 29: jmeter: command not found

why it is so?

**Comment by TannerGabriel** [comment]
You don't need to provide the `jmeter` command since the image uses that by default. Therefore you just need to provide the flags you want to use. See the following command for example:

```
docker run --volume `pwd`:/jmeter justb4/jmeter -n  -t /jmeter/load.jmx -JSERVER_URL=`printf -- "%s" "${URL##*/}"`  -l /jmeter/log.jtl
```

As you can see, I pass the flags directly after defining the Docker image without using the `jmeter` command in front.

**Comment by sjoshi-exiger** [comment]
Thanks for your response.
I have used jmeter as a tag for justb4/docker image. so that's why I was using that word. 

Now I am trying with image name. I am able to use it. but now the problem is it says 
'The file /workspace/CSVSample.jmx doesn't exist or can't be opened'

after giving this command
 docker run --volume E/****************/justb4-jmeter:/workspace justb4/jmeter -n -t /workspace/CSVSample.jmx -l /workspace/csvsample.jtl

**Comment by TannerGabriel** [comment]
It seems like the file is not found in the `workspace` directory, which means that there is probably an error with the volume (wrong directory, etc..). Therefore, I recommend using `PWD`, which stands for "print working directory" to use your current directory after navigating to where your test file is on your local machine.

```
docker run --volume `pwd`:/jmeter justb4/jmeter -n  -t /jmeter/load.jmx  -l /jmeter/log.jtl
```

In this example, I copy my current working directory of my local machine, which contains my test file to `/jmeter` of the container and can then use the test file inside of the container.

**Comment by sjoshi-exiger** [comment]
Thanks again.
I think it's a problem of "/" in path given for local directory. when I am using this command

docker run --volume E:\sameer\dockerContent\justb4-jmeter:/workspace justb4/jmeter -n -t /workspace/CSVSample.jmx -l /workspace/csvsample1.jtl

it's running properly. 

As per I know, when we are using --volume, it's making folder automatically in container if it doesn't exist.. so no question of specific folder that we should use like /workspace, /jmeter

**Comment by TannerGabriel** [comment]
So your issue is fixed now? If so, great. Let me know if you need anything else.

**Comment by sjoshi-exiger** [comment]
yes sure. Thanks.
