### ISSUE TITLE
Link in the documentation is broken

### ISSUE THREAD

**Issue by Vic152** [justb4/docker-jmeter#45]
Hello, I believe this URL no longer points to the right location.

See also: http://blog.novatec-gmbh.de/how-to-pass-command-line-properties-to-a-jmeter-testplan/

**Comment by justb4** [comment]
Ok, should be https://www.novatec-gmbh.de/en/blog/how-to-pass-command-line-properties-to-a-jmeter-testplan/. Fixing...
