### ISSUE TITLE
Build.sh link  does not work

### ISSUE THREAD

**Issue by harsh541** [justb4/docker-jmeter#5]
https://hub.docker.com/r/justb4/jmeter/ the build.sh link does not work.

**Comment by harsh541** [comment]
entrypoint.sh does not work either, not sure what that file is doing either.

**Comment by justb4** [comment]
Ok, the README on https://hub.docker.com/r/justb4/jmeter/  was copied from this GitHub README. Links were referring to GitHub files. Fixed most, and added a note.

`entrypoint.sh` is the main executable for the Docker Container, doing some setup and eventually calling `jmeter`.
