### ISSUE TITLE
question about plugins

### ISSUE THREAD

**Issue by leibson** [justb4/docker-jmeter#54]
I am kind of new to GitHub, so please bear with me.

I saw some discussion about support for JMeter plugins, but I do not see a plugins directory as you suggested.

Am I missing something?  

At present, I was going to create my own Docker image, based on this one, that retrieves and installs plugins.  

Thanks for making this.

**Comment by justb4** [comment]
Installing plugins should have been solved via #56. Hope this helps and you may want to close the issue.
