### ISSUE TITLE
Use MemAvailable when computing Java memory limits

### ISSUE THREAD

**Issue by darius-m** [justb4/docker-jmeter#55]
The entry point script currently uses `MemFree` to determine how much memory is available on the node. The amount of memory reported by this metric only includes the memory that is not used for any purpose, which means that it also excludes the memory used for caches. Linux likes to keep free memory occupied with cached files to reduce latency, which results in a low `MemFree` number.

The `MemAvailable` metric could be used instead, since it also includes the cache, that is automatically flushed when more memory is required for applications.

**Comment by justb4** [comment]
Good point! So we were always starting with too little memory...So ` awk '/MemAvailable/ { print int($2/1024) }' /proc/meminfo` would render the actual memory? Maybe you can make a PR for this?

**Comment by darius-m** [comment]
Indeed, `MemAvailable` should provide an estimate from the kernel on how much memory is available on the system for a new process. This [Superuser answer](https://superuser.com/a/980821) as well as the [original commit](https://github.com/torvalds/linux/commit/34e431b0ae398fc54ea69ff85ec700722c9da773) provide some more information.

**Comment by munlu-asp** [comment]
Hi All,
Does anybody know  how we run multiple .jmx files and put all these one single report ?

**Comment by justb4** [comment]
> Hi All, Does anybody know how we run multiple .jmx files and put all these one single report ?

@munlu-asp Please open a new issue, instead of a comment in an unrelated issue.
