### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by harsh541** [justb4/docker-jmeter#6]
docker run jmeterdocker
standard_init_linux.go:190: exec user process caused "no such file or directory"

After I run my docker image I get this error:

standard_init_linux.go:190: exec user process caused "no such file or directory"

Did anyone else get this? I think it's something to do with entrypoint.sp and the first line.

**Comment by justb4** [comment]
Looks a bit like this issue:
https://github.com/docker/labs/issues/215

Possibly a CRLF issue under Windows?

**Comment by justb4** [comment]
Closing, please reopen if still an issue.
