### ISSUE TITLE
Please fix README

### ISSUE THREAD

**Issue by dip-shintaro-ichino** [justb4/docker-jmeter#65]
Thank you for the useful Docker image.
I can't see [a link in README.md](https://github.com/justb4/docker-jmeter#user-defined-variables)
```markdown
See also: https://www.novatec-gmbh.de/en/blog/how-to-pass-command-line-properties-to-a-jmeter-testplan/ption
```

**Comment by justb4** [comment]
Fixed, was typo, thaks @dip-shintaro-ichino !
