### ISSUE TITLE
Not able to build the Dockerfile

### ISSUE THREAD

**Issue by Luzhmf** [justb4/docker-jmeter#9]
I'm trying to build the Dockerfile, and getting the following error:

The command '/bin/sh -c apk update && apk upgrade && apk add ca-certificates && update-ca-certificates 2>/dev/null || true && apk add --update openjdk8-jre tzdata curl unzip bash && rm -rf /var/cache/apk/* && mkdir -p /tmp/dependencies && curl -L --silent ${JMETER_DOWNLOAD_URL} > /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz && mkdir -p /opt && tar -xzf /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz -C /opt && rm -rf /tmp/dependencies' returned a non-zero code: 35

Please, can you guys help me?

**Comment by justb4** [comment]
Hard to tell from just that line, we need more info:

* what is your build command or do you use the `build.sh` script?
* on which OS and Docker version are you building?
* what is the value of your JMETER_VERSION variable? 
* what happens if you run `docker build  .`?
etc

**Comment by Luzhmf** [comment]
Sorry about the information, follow further about my case:

- I'm not using the `build.sh`, I'm trying to use `docker build`

- I'm using Docker 2.0.0.2 on windows 10

- The JMETER_VERSION was changed to 5.0
- When I try to run `docker build` I got the following result (image attached)
![2019-01-16_09-27-34](https://user-images.githubusercontent.com/5455669/51246260-2ab4c680-1971-11e9-90b2-84c1f398fcd9.jpg)

**Comment by justb4** [comment]
@Luzhmf this looks more like a local (Windows?) networking issue: "DNS lookup error", also I don't see `JMETER_VERSION` in the build args.

**Comment by wilsonmar** [comment]
I cloned this repo on my Mac, ran build.sh then run.sh. Got the same report output as under the trivial folder in the folder.

**Comment by justb4** [comment]
Yes, but the issue was seen in a Windows env. All I can see from the output above is that the error is very basic: not being able to fetch the Alpine base Docker Image because of a DNS error. This is AFAICS a local situation (proxy config?). I am closing this issue. @Luzhmf : please re-open if still a problem.
